version: "3"

services:
  provisioner:
    environment:
      - MAINSCRIPTS_DB_URI=mysql://mainscripts_db_user:mainscripts_db_password@mainscripts_db:3306/mainscripts
      - PRESEEDS_DB_URI=mysql://mainscripts_db_user:mainscripts_db_password@mainscripts_db:3306/mainscripts
      - PRESEEDSCRIPTS_DB_URI=mysql://mainscripts_db_user:mainscripts_db_password@mainscripts_db:3306/mainscripts
      - SERVICEDIR=src/services/provisioner
      - SERVICES=*.js
    build: .
    volumes:
      - .:/opt/pojntfx/provisioner:z
      - provisioner_node_modules:/opt/pojntfx/provisioner/node_modules:z
      - provisioner_tmp:/tmp/pojntfx/provisioner:z
    command: npm run start--watch
    networks:
      - main
      - mainscripts
    depends_on:
      - mainscripts_db
  pxeboot:
    environment:
      - SERVICEDIR=src/services/pxeboot
      - SERVICES=*.js
    build: .
    volumes:
      - pxeboot_node_modules:/opt/pojntfx/provisioner/node_modules:z
      - pxeboot_tmp:/tmp/pojntfx/provisioner:z
      - pxeboot_etc:/etc:z
    command: npm run start--watch
    network_mode: host
    cap_add:
      - NET_ADMIN
    ports:
      - "57:57"
      - "67:67"
      - "69:69"
  dns:
    environment:
      - SERVICEDIR=src/services/dns
      - SERVICES=*.js
    build: .
    volumes:
      - dns_node_modules:/opt/pojntfx/provisioner/node_modules:z
      - dns_tmp:/tmp/pojntfx/provisioner:z
    command: npm run start--watch
    network_mode: host
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53"
  gateway:
    environment:
      - GATEWAY_DB_URI=mysql://mainscripts_db_user:mainscripts_db_password@mainscripts_db:3306/mainscripts
      - SERVICEDIR=src/services/gateway
      - SERVICES=*.js
    build: .
    volumes:
      - gateway_node_modules:/opt/pojntfx/provisioner/node_modules:z
    command: npm run start--watch
    networks:
      - main
      - mainscripts
    ports:
      - 3000:3000
    depends_on:
      - pxeboot
      - provisioner
      - mainscripts_db
  mainscripts_db:
    environment:
      - MARIADB_ROOT_PASSWORD=mainscripts_db_root_password
      - MARIADB_USER=mainscripts_db_user
      - MARIADB_PASSWORD=mainscripts_db_password
      - MARIADB_DATABASE=mainscripts
    image: bitnami/mariadb:10.2.21
    volumes:
      - mainscripts_db:/bitnami/mariadb
    networks:
      - mainscripts

volumes:
  provisioner_node_modules:
  provisioner_tmp:
  pxeboot_node_modules:
  pxeboot_tmp:
  pxeboot_etc:
  dns_node_modules:
  dns_tmp:
  gateway_node_modules:
  mainscripts_db:

networks:
  main:
  mainscripts:
