apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provisioner-nats-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provisioner-nats
spec:
  selector:
    matchLabels:
      app: provisioner-nats
  template:
    metadata:
      labels:
        app: provisioner-nats
    spec:
      containers:
        - name: provisioner-nats
          image: nats:1.4.1
          resources:
            limits:
              memory: 128Mi
              cpu: 80m
          ports:
            - containerPort: 4222
          volumeMounts:
            - name: provisioner-nats-data
              mountPath: /data
      volumes:
        - name: provisioner-nats-data
          persistentVolumeClaim:
            claimName: provisioner-nats-data
---
apiVersion: v1
kind: Service
metadata:
  name: provisioner-nats
spec:
  selector:
    app: provisioner-nats
  ports:
    - port: 4222
      targetPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: provisioner-nats-public
spec:
  type: NodePort
  selector:
    app: provisioner-nats
  ports:
    - port: 4222
      targetPort: 4222
      nodePort: 30369
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: provisioner-nats-public
data:
  TRANSPORTER: nats://192.168.99.100:30369
